create table if not exists public.notification_preferences (
  user_id bigint primary key references public.users(id) on delete cascade,
  whatsapp_enabled boolean not null default false,
  email_enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.notification_outbox (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  recipient_user_id bigint not null references public.users(id) on delete cascade,
  channel text not null check (channel in ('whatsapp','email','sms')),
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending','sent','failed')),
  attempts integer not null default 0,
  available_at timestamptz not null default now(),
  sent_at timestamptz,
  last_error text,
  dedupe_key text not null,
  unique (school_id, dedupe_key)
);
create index if not exists ix_notification_outbox_pending on public.notification_outbox(status, available_at);
