-- Portail Scolaire — schéma PostgreSQL initial
-- Compatible avec la migration depuis l'ancien modèle SQLite.
create extension if not exists pgcrypto;

create table if not exists public.schools (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  city text not null default '',
  academic_year text not null default '',
  parent_bulletin_min_avg numeric not null default 10,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  description text not null default '',
  address text not null default '',
  phone text not null default '',
  contact_email text not null default '',
  hours text not null default ''
);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  school_id bigint references public.schools(id) on delete cascade,
  username text not null,
  email text,
  phone text,
  password_hash text not null,
  role text not null check (role in ('superadmin','admin','teacher','student','parent')),
  first_name text not null default '',
  last_name text not null default '',
  active boolean not null default true,
  must_change_password boolean not null default false,
  created_at timestamptz not null default now()
);
create unique index if not exists ux_users_school_username on public.users (coalesce(school_id, 0), username);
create index if not exists ix_users_school_role on public.users (school_id, role);

create table if not exists public.levels (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  name text not null,
  position integer not null default 0,
  unique (school_id, name)
);
create table if not exists public.series (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  name text not null,
  unique (school_id, name)
);
create table if not exists public.classes (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  level_id bigint not null references public.levels(id),
  series_id bigint references public.series(id),
  name text not null,
  unique (school_id, name)
);
create table if not exists public.subjects (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  name text not null,
  unique (school_id, name)
);
create table if not exists public.coefficients (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  level_id bigint not null references public.levels(id) on delete cascade,
  series_id bigint references public.series(id) on delete cascade,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  coef numeric not null check (coef > 0)
);
create unique index if not exists ux_coef on public.coefficients (school_id, level_id, coalesce(series_id, 0), subject_id);
create table if not exists public.terms (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  name text not null,
  position integer not null,
  status text not null default 'upcoming' check (status in ('upcoming','open','closed')),
  closed_at timestamptz,
  unique (school_id, name)
);
create table if not exists public.students (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  user_id bigint not null unique references public.users(id) on delete cascade,
  class_id bigint not null references public.classes(id),
  matricule text not null default ''
);
create index if not exists ix_students_class on public.students (school_id, class_id);
create table if not exists public.parent_students (
  parent_id bigint not null references public.users(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  primary key (parent_id, student_id)
);
create table if not exists public.teaching_assignments (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  teacher_id bigint not null references public.users(id) on delete cascade,
  class_id bigint not null references public.classes(id) on delete cascade,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  unique (teacher_id, class_id, subject_id)
);
create table if not exists public.grades (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  student_id bigint not null references public.students(id),
  subject_id bigint not null references public.subjects(id),
  term_id bigint not null references public.terms(id),
  type text not null check (type in ('interro','devoir')),
  idx integer not null check (idx between 1 and 6),
  value numeric not null check (value between 0 and 20),
  created_by bigint references public.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  unique (student_id, subject_id, term_id, type, idx)
);
create index if not exists ix_grades_term on public.grades (school_id, term_id);
create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  class_id bigint not null references public.classes(id),
  subject_id bigint not null references public.subjects(id),
  date date not null,
  status text not null check (status in ('present','absent','late')),
  justified boolean not null default false,
  recorded_by bigint references public.users(id) on delete set null,
  unique (student_id, subject_id, date)
);
create index if not exists ix_att_school_date on public.attendance (school_id, date);
create table if not exists public.justifications (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  attendance_id bigint not null references public.attendance(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  submitted_by bigint references public.users(id) on delete set null,
  reason text not null,
  file_name text,
  original_name text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  reviewed_by bigint references public.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);
create table if not exists public.chapters (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  class_id bigint not null references public.classes(id) on delete cascade,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  teacher_id bigint references public.users(id) on delete set null,
  title text not null,
  position integer not null default 0,
  status text not null default 'todo' check (status in ('todo','in_progress','done')),
  updated_at timestamptz not null default now()
);
create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  class_id bigint not null references public.classes(id) on delete cascade,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  teacher_id bigint references public.users(id) on delete set null,
  date date not null,
  content text not null,
  homework text not null default '',
  created_at timestamptz not null default now()
);
create table if not exists public.archives (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  class_id bigint not null references public.classes(id) on delete cascade,
  subject_id bigint not null references public.subjects(id) on delete cascade,
  uploaded_by bigint references public.users(id) on delete set null,
  title text not null,
  file_name text not null,
  original_name text not null,
  size bigint not null default 0,
  created_at timestamptz not null default now()
);
create table if not exists public.discipline (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  class_id bigint not null references public.classes(id),
  recorded_by bigint references public.users(id) on delete set null,
  kind text not null check (kind in ('positive','negative')),
  description text not null,
  date date not null,
  created_at timestamptz not null default now()
);
create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  title text not null,
  body text not null,
  category text not null default 'news' check (category in ('news','event','info')),
  audience text not null default 'members' check (audience in ('public','members')),
  event_date date,
  pinned boolean not null default false,
  image_name text,
  author_id bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists ix_ann_school on public.announcements (school_id, audience, created_at);
create table if not exists public.announcement_images (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  announcement_id bigint not null references public.announcements(id) on delete cascade,
  file_name text not null,
  position integer not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists ix_annimg_ann on public.announcement_images (announcement_id, position);
create table if not exists public.password_resets (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  used_at timestamptz
);

-- Les premières routes utilisent encore un service serveur protégé. RLS est activé
-- dès maintenant afin d'éviter une exposition accidentelle via l'API publique.
-- Les politiques métier détaillées seront ajoutées avec la bascule Supabase Auth.
do $$ declare t text; begin
  foreach t in array array['schools','users','levels','series','classes','subjects','coefficients','terms','students','parent_students','teaching_assignments','grades','attendance','justifications','chapters','lessons','archives','discipline','announcements','announcement_images','password_resets'] loop
    execute format('alter table public.%I enable row level security', t);
  end loop;
end $$;

create or replace function public.current_school_id() returns bigint
language sql stable security definer set search_path = public
as $$ select nullif(current_setting('request.jwt.claims', true)::jsonb ->> 'school_id', '')::bigint $$;

create policy schools_public_read on public.schools for select using (active = true);
create policy tenant_read_schools on public.schools for select using (id = public.current_school_id());

-- Aucun accès anonyme aux données privées : les écritures restent serveur-only
-- pendant la phase de migration et seront remplacées par des policies par rôle.
